# Generated by Django 3.2 on 2021-05-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.JSONField(null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fio',
            field=models.CharField(max_length=200, null=True, verbose_name='Ф.И.О.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sni14',
            field=models.CharField(max_length=14, null=True, verbose_name='СНИЛС'),
        ),
    ]
