# Generated by Django 3.2 on 2021-05-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_log', '0002_auto_20210503_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at'], 'verbose_name': 'Примечание', 'verbose_name_plural': 'Примечания'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='fio',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Ф.И.О.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sni14',
            field=models.CharField(blank=True, default='123-456-789 00', max_length=14, verbose_name='СНИЛС'),
        ),
    ]
