# Generated by Django 3.2 on 2021-05-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FastPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('category', models.IntegerField(choices=[(0, 'Сайт'), (1, 'Приложение'), (2, 'Портал')], verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Точка',
                'verbose_name_plural': 'Точки',
                'ordering': ['title'],
            },
        ),
    ]
